server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true               #开启从注册中心中创建路由的功能，理由微服务名进行路由
      routes:
        - id: CLOUD-PROVIDER-PAYMENT1              #路由ID，没有固定的规则但要求唯一
          #uri:http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE          #匹配后提供服务的路由地址
          predicates:                              #断言，路径相匹配进行路由
            - Path=/payment/getById/**
            - After=2021-01-01T00:00:00.000+00:00[Asia/Shanghai]  #在指定时间之后
            #- Before=
            #- Between=
            #如果以CookieName为key的值匹配正则表达式，则去路由，否则不执行
            #需要指定两个参数，一个是CookieName，一个是正则表达式
            #- Cookie=Jren,Haiberg
            #同Cookie
            #- Header=Jren,\d+
            #- Method=GET
            #- Query=ids,222

        - id: CLOUD-PROVIDER-PAYMENT2
          #uri:http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/discovery/**